version: 2
updates:
  - package-ecosystem: gradle
    directory: "/"
    schedule:
      interval: daily
      time: "00:00"
      timezone: "Europe/Warsaw"
    open-pull-requests-limit: 10
    ignore:
      - dependency-name: org.spigotmc:spigot-api
        versions:
          - "> 1.8.8-R0.1-SNAPSHOT"
