update:
  check: true
  simple: false #Wylacza kolory w konsoli jesli jest ustawione na true
  time: 180 #Czas co jaki ma sprawdzac dostepnosc aktualizacjie w minutach
#Update'y wychodza rzadko ale zawieraja duzo wiec radzimy zostawic to wlaczone
#Jesli mimo najnowszej wersji wiadomosc jest dalej wysylana mozna wylaczyc
top:
  autoupdate:
    execute: true #Automatyczna aktualizacja topek graczy i gildii
    time: 600 #Czas w sekundach po jakim topka się restartuje
messages:
  noperm: "&bFunnySkAddon &8> &7Niestety nie posiadasz uprawnien." #Wiadomość wsyłana gdy gracz nie ma uprawnień

