update:
  #Update'y wychodzą rzadko ale zawierają dużo, radzimy więc zostawić to włączone
  #Jesli mimo najnowszej wersji wiadomość jest dalej wysylana mozna wyłączyc
  check: true
  #Ustawione na false zwraca również "niepełne" wydania (Pre-Release)
  onlyFullReleases: true
  #Wyłącza kolory w konsoli jeśli jest ustawione na true
  simple: false
  #Czas co jaki ma być sprawdzana dostępność aktualizacji w minutach
  time: 180
messages:
  #Wiadomość wsyłana gdy gracz nie ma uprawnień do komendy /funnyskaddon
  noperm: "&bFunnySkAddon &8> &7Niestety nie posiadasz uprawnien."

