name: FunnySkAddon
version: 2.1.0-Beta
authors: [Peridot, LloydPL]
description: Dodatek do pluginu Skript dodajacy wsparcie pluginu gildyjnego FunnyGuilds
website: funnyskaddon.pl
main: pl.funnyskaddon.FunnySkAddon
softdepend: [Skript, FunnyGuilds]

commands:
  funnyskaddon:
    aliases: [fsa]
    description: Wyswietla informacje o pluginie FunnySkAddon

permissions:
  funnyskaddon.cmd:
    description: Uprawnienie do glownej (i jedynej komendy) w pluginie, /funnyskaddon
    default: op
