name: FunnySkAddon-Extended
version: 1.9
authors: [Peridot, LloydPL]
description: Dodatek do pluginu Skript dodajacy wsparcie pluginu gildyjnego FunnyGuilds
website: mlgroup.pl
main: pl.funnyskaddon.core.FunnySkAddon
softdepend: [Skript, FunnyGuilds]

commands:
  funnyskaddon:
    aliases: [fsa]
    description: Wyswietla informacje o pluginie FunnySkAddon
