name: FunnySkAddon
version: @version@
authors: [Peridot, LloydPL]
description: Official Skript addon adding support for FunnyGuilds
website: funnyskaddon.pl
main: pl.funnyskaddon.FunnySkAddon
softdepend: [Skript, FunnyGuilds]
api-version: 1.13

commands:
  funnyskaddon:
    aliases: [fsa]
    description: Displays information about the plugin (version, author, etc.)

permissions:
  funnyskaddon.cmd:
    description: Permission to use plugin's command
    default: op
  funnyskaddon.update.check:
    description: Permission to display information about the availability of plugin update
    default: op
